<header>
    <h2>Product Table</h2>
    <table class="table table-striped table-hover my-4">
        <caption>Product Table</caption>
        <thead>
            <tr>
                <th>Name</th>
                <th>Company</th>
                <th>Type</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            <?php
            echo $display;
            ?>
        </tbody>
    </table>
</header>