<header>
    <div class="row my-3">
        <h2 class="col-9">Product Form</h2>
        <a class="btn btn-primary col-3" href="/product/display">Product Table</a>
    </div>
    <form class="row form my-4" action="/product/add" method="post">
        <div class="col-6">
            <label for="name">Name</label>
            <input class="form-control" type="text" name="name" id="name">
        </div>
        <div class="col-6">
            <label for="company">Company</label>
            <input class="form-control" type="text" name="company" id="company">
        </div>
        <div class="col-6">
            <label for="pincode">Type</label>
            <input class="form-control" type="text" name="type" id="Type">
        </div>
        <div class="col-6">
            <label for="qunatity">Quantity</label>
            <input class="form-control" type="text" name="qunatity" id="qunatity">
        </div>
        <button type="submit" class="btn btn-primary col-2 m-3">Add</button>
    </form>

</header>