<header>
    <h2>Order Table</h2>
    <table class="table table-striped table-hover my-4">
        <caption>Order Table</caption>
        <thead>
            <tr>
                <th>Name</th>
                <th>Event</th>
                <th>Key</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php
            echo $display;
            ?>
        </tbody>
    </table>
</header>